### ISSUE TITLE
Publisher example not executable as is

### ISSUE THREAD

**Issue by apete** [exxeleron/qJava#10]
Running the Publisher example, as it is, doesn't work, and I see no instructions regarding what needs to be done in order to prepare for execution.

I'm new to KDB, but I've tried to figure what's needed - like creating a table named "ask". So far I haven't succeeded.

Could you please add descriptions of prerequisites for the various examples?

Publisher, TickClient, TickSubscriber doesn't run as is, but AsycQuery, Console, Subscriber and SyncQuery does.

**Comment by bartosz-dolecki** [comment]
Hello,

We added instructions on how to run all samples. Just go to

https://github.com/exxeleron/qJava/tree/master/src/sample/java

the instructions should be displayed below.

Cheers,
Bartosz

**Comment by apete** [comment]
Thank you!
